name: Check Vite Build

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
    branches: [main]

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22' # https://github.com/actions/node-versions/releases
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build
